fail_fast: True

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: master
  hooks:
  - id: check-added-large-files
    name: check-added-large-files
    args: ['--maxkb=1000']
    stages: [commit]
    exclude: tests/streetview/known_results.pickle

- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [commit]
    language: system
    entry: poetry run isort
    types: [python]

  - id: black
    name: black
    stages: [commit]
    language: system
    entry: poetry run black
    types: [python]

  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: poetry run flake8
    exclude: (^research/*|^tests/streetview/requests/*)
    types: [python]

  - id: mypy
    name: mypy
    stages: [commit]
    language: system
    entry: poetry run mypy
    types: [python]
    exclude: (^research/*|^tests/streetview/requests/*)
    pass_filenames: true

  - id: pylint
    name: pylint
    stages: [commit]
    language: system
    exclude: (^research/*|^tests/streetview/requests/*)
    entry: poetry run pylint
    types: [python]
    pass_filenames: true
