fail_fast: True

repos:
- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [commit]
    language: system
    entry: isort
    types: [python]

  - id: black
    name: black
    stages: [commit]
    language: system
    entry: black
    types: [python]

  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: flake8
    types: [python]

  - id: mypy
    name: mypy
    stages: [commit]
    language: system
    entry: mypy
    types: [python]
    pass_filenames: true

  - id: pylint
    name: pylint
    stages: [commit]
    language: system
    entry: pylint
    types: [python]
    pass_filenames: true
